# Generated by Django 5.0.2 on 2024-02-25 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=400)),
                ("feed_url", models.CharField(max_length=400)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(null=True)),
                ("image", models.CharField(max_length=400, null=True)),
                ("language", models.CharField(max_length=20, null=True)),
                ("last_build_date", models.DateTimeField(null=True)),
                ("pub_date", models.DateTimeField(null=True)),
                ("generator", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=400)),
                ("description", models.TextField(null=True)),
                ("image", models.TextField(null=True)),
                ("pub_date", models.DateTimeField()),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.feed",
                    ),
                ),
            ],
            options={
                "ordering": ["-pub_date"],
            },
        ),
    ]
