# Generated by Django 5.0.2 on 2024-02-25 21:11

import api.models
import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="key",
            field=models.CharField(
                default=api.models.gen_key, max_length=16, unique=True
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, populate_from="title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="key",
            field=models.CharField(
                default=api.models.gen_key, max_length=16, unique=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, populate_from="title"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feed",
            name="feed_url",
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="api.feed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("feed", "user")},
            },
        ),
    ]
