# Generated by Django 5.0.2 on 2024-02-26 01:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_feed_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="title"
            ),
        ),
    ]
