# Generated by Django 5.0.2 on 2024-02-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_feed_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="last_refresh",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="next_refresh",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="ttl",
            field=models.IntegerField(null=True),
        ),
    ]
