# Generated by Django 5.0.2 on 2024-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_item_guid"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="next_refresh",
            field=models.DateTimeField(null=True),
        ),
    ]
