# Generated by Django 5.0.2 on 2024-03-02 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_itemfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
