# Generated by Django 5.0.2 on 2024-03-27 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="joined_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
